# Site settings
#
# Docs: https://jekyllrb.com/docs/configuration/
title: QUnit
description: The powerful, easy-to-use JavaScript testing framework.
url: "https://qunitjs.com"
# For pages (not blog posts) this is equivalant to /:title/
permalink: /:year/:month/:day/:title/
lang: en
timezone: UTC
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"
sass:
  # https://jekyllrb.com/docs/assets/#sassscss
  style: compressed
  sourcemap: never
exclude:
  # Don't include these files in the website
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME
  - vendor
  - build

# Theme
theme: null
remote_theme: https://github.com/qunitjs/jekyll-theme-amethyst@2522216


# Theme settings
#
# Amethyst theme options are documented at:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/config.md
#
amethyst:
  # We keep a classic ICO file as well, for compat with de-facto standard
  # machine discovery, e.g. search engines and analytics software.
  favicon: /favicon.svg
  home_href:
  header_logo:
    src: /img/logo-with-colored-text.svg
    width: 250
    height: 72
  edituri_base: https://github.com/qunitjs/qunitjs.com/blob/main/
  release_base: https://github.com/qunitjs/qunit/releases/tag/
  mastodon: https://mastodon.technology/@qunitjs
  twitter: qunitjs
  github: qunitjs
  gitter: qunitjs/qunit
  algolia:
    search_only_api_key: f492bec49e061a41cb8f57128483fd16
    sources:
      - index: qunitjs-api
        base: https://api.qunitjs.com
      - index: qunitjs


# Backend search settings
#
# This applies to the 'jekyll algolia' command, which is typically
# run from an after a commit is merged. The settings are documented at:
# https://github.com/algolia/jekyll-algolia
#
# To learn how to set this up, refer to:
# https://github.com/qunitjs/jekyll-theme-amethyst/blob/main/docs/getting-started.md#enable-algolia-search
#
algolia:
  application_id: EQYECMT6Q0
  # Which index_name the 'jekyll algolia' command will create or update.
  index_name: qunitjs
  nodes_to_index: 'p,li,tr,pre'
  files_to_exclude:
    # Index destination instead of intermediary
    - guides.md


# Blog archives
#
# Docs: https://github.com/jekyll/jekyll-archives/
jekyll-archives:
  enabled:
    - year
  layout: posts-year
  permalinks:
    year: "/:year/"
